#FROM python:3.10-slim-bookworm
FROM registry.access.redhat.com/ubi9/python-311:latest

WORKDIR /app

RUN dnf update -y \
 && dnf clean all \
 && rm -rf /var/cache/yum \
 && python3 -m pip install "openbb[all]" \
 && python3 -m pip install openbb-platform-api

EXPOSE 6900

ENTRYPOINT ["openbb-api", "--host", "0.0.0.0", "--login"]
